# Default values for phpmyadmin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image: quay.io/kubernetes_incubator/nfs-provisioner:v1.0.8

ingress:
  enabled: false

nfs:
  provisioner: example.com/nfs
  storageClass: example-nfs

service:
  enabled: true
  type: "ClusterIP"

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 2Gi
  storageClass: standard
  
resources:
  requests:
    cpu: 50m
    memory: 100Mi

