# Default values for phpmyadmin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image: phpmyadmin/phpmyadmin:4.7.3-1

imagePullPolicy: IfNotPresent

ingress:
  enabled: false

service:
  enabled: false
  type: "ClusterIP"

resources:
  requests:
    cpu: 50m
    memory: 100Mi

