apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  credentials.json: |-
    {{ .Values.serviceAccountKey }}
  cloudsql-password: {{ default "" .Values.cloudsqlPassword | b64enc | quote }}
  cloudsql-root-password: {{ default "" .Values.cloudsqlRootPassword | b64enc | quote }}
